MODEL:
  META_ARCHITECTURE: "CenterNetDetector"
  PROPOSAL_GENERATOR:
    NAME: "CenterNet"
  PIXEL_STD: [57.375, 57.120, 58.395]
  BACKBONE:
    NAME: "my_build_p37_dla_bifpn_cbam_backbone"
  BIFPN:
    OUT_CHANNELS: 160
    NUM_LEVELS: 5
    NUM_BIFPN: 3
  DLA:
    NUM_LAYERS: 34
    NORM: "SyncBN"
  FPN:
    IN_FEATURES: ["dla3", "dla4", "dla5"]
  CENTERNET:
    FPN_STRIDES: [8, 16, 32]
    SOI: [[0, 64], [48, 192], [128, 1000000]]
    NUM_CLASSES: 50
    IN_FEATURES: ['p3', 'p4', 'p5']
  WEIGHTS: "./models/CenterNet/CenterNet-FFA_N50.pth"
DATASETS:
  TRAIN: ("my_indoor_dataset_train",)
  TEST: ("my_indoor_dataset_val",)
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  MAX_ITER: 360000
  BASE_LR: 0.06
  IMS_PER_BATCH: 16
  CHECKPOINT_PERIOD: 90001
INPUT:
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 640
  MIN_SIZE_TEST: 608
  MAX_SIZE_TEST: 900
TEST:
  EVAL_PERIOD: 40000
OUTPUT_DIR: "./output/MY/CBAM/auto"