MODEL:
  META_ARCHITECTURE: "CenterNetDetector"
  PROPOSAL_GENERATOR:
    NAME: "CenterNet"
  PIXEL_STD: [57.375, 57.120, 58.395]
  BACKBONE:
    NAME: "my_build_p37_dla_bifpn_cbam_backbone"
  BIFPN:
    OUT_CHANNELS: 160
    NUM_LEVELS: 5
    NUM_BIFPN: 3
  DLA:
    NUM_LAYERS: 34
    NORM: "BN"
  FPN:
    IN_FEATURES: ["dla3", "dla4", "dla5"]
  CENTERNET:
    IN_FEATURES: ['p3', 'p4', 'p5']
    FPN_STRIDES: [8, 16, 32]
    SOI: [[0, 64], [48, 192], [128, 1000000]]
    NUM_CLS_CONVS: 1
    NUM_BOX_CONVS: 1
    REG_WEIGHT: 1.
    MORE_POS: True
    HM_FOCAL_ALPHA: 0.25
  WEIGHTS: "./models/ImageNetPretrained/MSRA_R-50.pkl"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  MAX_ITER: 520000
  BASE_LR: 0.05
  IMS_PER_BATCH: 16
  WEIGHT_DECAY: 0.0001
  CHECKPOINT_PERIOD: 100000
  CLIP_GRADIENTS:
    ENABLED: True
  RESET_ITER: TRUE
INPUT:
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 640
  MIN_SIZE_TEST: 608
  MAX_SIZE_TEST: 900
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "./output/MY/CBAM/auto"