MODEL:
  META_ARCHITECTURE: "CenterNetDetector"
  PROPOSAL_GENERATOR:
    NAME: "CenterNet"
  PIXEL_STD: [57.375, 57.120, 58.395]
  BACKBONE:
    NAME: "my_build_p35_dla_bifpn_cbam_backbone"
  BIFPN:
    OUT_CHANNELS: 160
    NUM_LEVELS: 3
    NUM_BIFPN: 3
  DLA:
    NUM_LAYERS: 34
    NORM: "BN"
  FPN:
    IN_FEATURES: ["dla3", "dla4", "dla5"]
  CENTERNET:
    IN_FEATURES: ['p3', 'p4', 'p5']
    FPN_STRIDES: [8, 16, 32]
    SOI: [[0, 64], [48, 192], [128, 1000000]]
    NUM_CLS_CONVS: 1
    NUM_BOX_CONVS: 1
    REG_WEIGHT: 1.
  WEIGHTS: "./models/ImageNetPretrained/MSRA_R-50.pkl"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (300000, 340000)
  MAX_ITER: 360000
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 4000
  WARMUP_FACTOR: 0.00025
  CLIP_GRADIENTS:
    ENABLED: True
INPUT:
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 640
  MIN_SIZE_TEST: 608
  MAX_SIZE_TEST: 900
TEST:
  EVAL_PERIOD: 5000
DATALOADER:
  NUM_WORKERS: 8
OUTPUT_DIR: "./output/MY/auto"