_BASE_: "Base_S4_DLA.yaml"
MODEL:
  WEIGHTS: "./models/CenterNet/CenterNet-S4_DLA_8x.pth"
DATASETS:
  TRAIN: ("my_indoor_dataset_train",)
  TEST: ("my_indoor_dataset_val",)
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  MAX_ITER: 80000
  BASE_LR: 0.01
  IMS_PER_BATCH: 8
  WEIGHT_DECAY: 0.00005
  CHECKPOINT_PERIOD: 41000
  CLIP_GRADIENTS:
    ENABLED: True
  RESET_ITER: TRUE  
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "./output/MY/auto"
