_BASE_: "Base-CenterNet-FPN.yaml"
CENTERNET:
    MORE_POS: True
  WEIGHTS: "./models/CenterNet/CenterNet-FPN_R50_1x.pth"
DATASETS:
  TRAIN: ("my_indoor_dataset_train",)
  TEST: ("my_indoor_dataset_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (65000, 72000)
  MAX_ITER: 80000
  CHECKPOINT_PERIOD: 41000
  WARMUP_ITERS: 4000
  WARMUP_FACTOR: 0.00015
  CLIP_GRADIENTS:
    ENABLED: True
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "./output/MY/auto"
