MODEL:
  META_ARCHITECTURE: "CenterNetDetector"
  PROPOSAL_GENERATOR:
    NAME: "CenterNet"
  PIXEL_STD: [57.375, 57.120, 58.395]
  BACKBONE:
    NAME: "build_dla_backbone"
  DLA:
    NORM: "BN"
  CENTERNET:
    NUM_CLASSES: 8
    IN_FEATURES: ["dla2"]
    FPN_STRIDES: [4]
    SOI: [[0, 1000000]]
    NUM_CLS_CONVS: 1
    NUM_BOX_CONVS: 1
    REG_WEIGHT: 1.
DATASETS:
  TRAIN: ("nurse_train",)
  TEST: ("nurse_val",)
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  MAX_ITER: 5000
  BASE_LR: 0.04
  IMS_PER_BATCH: 8
  WEIGHT_DECAY: 0.0001
  CHECKPOINT_PERIOD: 9999999
  CLIP_GRADIENTS:
    ENABLED: True
INPUT:
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 640
  MIN_SIZE_TEST: 608
  MAX_SIZE_TEST: 900
TEST:
  EVAL_PERIOD: 7500
DATALOADER:
  NUM_WORKERS: 8
OUTPUT_DIR: "output/auto"
